from sqlalchemy.dialects import mysql
from .. import *


class Node(db.Model):
    __tablename__ = "ordered_nodes"

    id = db.Column(db.Integer, primary_key=True)
    ott = db.Column(db.Integer)
    parent = db.Column(db.Integer, nullable=False)
    real_parent = db.Column(db.Integer, nullable=False)
    node_rgt = db.Column(db.Integer, nullable=False)
    leaf_lft = db.Column(db.Integer, nullable=False)
    leaf_rgt = db.Column(db.Integer, nullable=False)
    name = db.Column(db.String(190))
    age = db.Column(db.Float)
    wikidata = db.Column(db.Integer)
    wikipedia_lang_flag = db.Column(db.Integer)
    eol = db.Column(db.Integer)
    raw_popularity = db.Column(db.Float)
    popularity = db.Column(db.Float)
    ncbi = db.Column(db.Integer)
    ifung = db.Column(db.Integer)
    irmng = db.Column(db.Integer)
    gbif = db.Column(db.Integer)
    ipni = db.Column(db.Integer)
    vern_synth = db.Column(db.Text)
    rep1 = db.Column(db.Integer)
    rep2 = db.Column(db.Integer)
    rep3 = db.Column(db.Integer)
    rep4 = db.Column(db.Integer)
    rep5 = db.Column(db.Integer)
    rep6 = db.Column(db.Integer)
    rep7 = db.Column(db.Integer)
    rep8 = db.Column(db.Integer)
    rtr1 = db.Column(db.Integer)
    rtr2 = db.Column(db.Integer)
    rtr3 = db.Column(db.Integer)
    rtr4 = db.Column(db.Integer)
    rtr5 = db.Column(db.Integer)
    rtr6 = db.Column(db.Integer)
    rtr7 = db.Column(db.Integer)
    rtr8 = db.Column(db.Integer)
    rpd1 = db.Column(db.Integer)
    rpd2 = db.Column(db.Integer)
    rpd3 = db.Column(db.Integer)
    rpd4 = db.Column(db.Integer)
    rpd5 = db.Column(db.Integer)
    rpd6 = db.Column(db.Integer)
    rpd7 = db.Column(db.Integer)
    rpd8 = db.Column(db.Integer)
    iucnNE = db.Column(db.Integer)
    iucnLC = db.Column(db.Integer)
    iucnNT = db.Column(db.Integer)
    iucnVU = db.Column(db.Integer)
    iucnEN = db.Column(db.Integer)
    iucnCR = db.Column(db.Integer)
    iucnEW = db.Column(db.Integer)
    iucnEX = db.Column(db.Integer)
    popleaf = db.Column(db.Integer)
    popleaf_ott = db.Column(db.Integer)
    rpd9 = db.Column(db.Integer)
    rpd9 = db.Column(db.Integer)

    def __repr__(self):
        return "<Node %r>" % self.name
